### ISSUE TITLE
Error when "pull_request_closed" event is received

### ISSUE THREAD

**Issue by chrismytton** [everypolitician/pull_request_preview#6]
When the `pull_request_closed` event is triggered we're seeing errors like this:

```
3 TID-os3y1u3m0 PullRequestPreview JID-92daf1b72d64684bd0f3e2a3 INFO: start 
3 TID-os3y1u3m0 PullRequestPreview JID-92daf1b72d64684bd0f3e2a3 INFO: fail: 0.892 sec 
3 TID-os3y1u3m0 WARN: {"class"=>"PullRequestPreview", "args"=>["pull_request_closed", "14520", "https://cdn.rawgit.com/everypolitician/everypolitician-data/6ca7bf24c5837d85b9ed4ff2790b321aaf89b965/countries.json"], "retry"=>true, "queue"=>"default", "jid"=>"92daf1b72d64684bd0f3e2a3", "created_at"=>1469540058.8233361, "enqueued_at"=>1469549802.9997616, "error_message"=>"POST https://api.github.com/repos/everypolitician/viewer-sinatra/pulls: 422 - Validation Failed\nError summary:\n  resource: PullRequest\n  field: head\n  code: invalid // See: https://developer.github.com/v3/pulls/#create-a-pull-request", "error_class"=>"Octokit::UnprocessableEntity", "failed_at"=>1469540059.8794055, "retry_count"=>9, "retried_at"=>1469549803.8927119} 
3 TID-os3y1u3m0 WARN: Octokit::UnprocessableEntity: POST https://api.github.com/repos/everypolitician/viewer-sinatra/pulls: 422 - Validation Failed 
Error summary: 
  resource: PullRequest 
  field: head 
  code: invalid // See: https://developer.github.com/v3/pulls/#create-a-pull-request 
3 TID-os3y1u3m0 WARN: /app/vendor/bundle/ruby/2.2.0/gems/octokit-4.2.0/lib/octokit/response/raise_error.rb:16:in `on_complete' 
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:9:in `block in call' 
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:57:in `on_complete' 
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/response.rb:8:in `call' 
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:73:in `perform_with_redirection' 
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.2.0/lib/octokit/middleware/follow_redirects.rb:61:in `call' 
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/rack_builder.rb:139:in `build_response' 
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:377:in `run_request' 
/app/vendor/bundle/ruby/2.2.0/gems/faraday-0.9.2/lib/faraday/connection.rb:177:in `post' 
/app/vendor/bundle/ruby/2.2.0/gems/sawyer-0.6.0/lib/sawyer/agent.rb:94:in `call' 
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.2.0/lib/octokit/connection.rb:154:in `request' 
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.2.0/lib/octokit/connection.rb:28:in `post' 
/app/vendor/bundle/ruby/2.2.0/gems/octokit-4.2.0/lib/octokit/client/pull_requests.rb:57:in `create_pull_request' 
/app/lib/viewer_sinatra.rb:104:in `create_pull_request' 
/app/lib/viewer_sinatra.rb:54:in `on_closed' 
/app/app.rb:37:in `perform' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:150:in `execute_job' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:132:in `block (2 levels) in process' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:127:in `block in invoke' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/retry_jobs.rb:74:in `call' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:11:in `block in call' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/logging.rb:30:in `with_context' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/server/logging.rb:7:in `call' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:129:in `block in invoke' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `call' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/middleware/chain.rb:132:in `invoke' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:127:in `block in process' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:166:in `stats' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:126:in `process' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:79:in `process_one' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/processor.rb:67:in `run' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:16:in `watchdog' 
/app/vendor/bundle/ruby/2.2.0/gems/sidekiq-4.0.1/lib/sidekiq/util.rb:24:in `block in safe_thread'
```

**Comment by chrismytton** [comment]
Looks like this error occurs if an everypolitician-data pull request gets closed before the parallel viewer-sinatra one has been created. We're trying to create a viewer-sinatra pull request, even if the everypolitician-data pull request is being closed or merged.
